version: '3.9'
name: shipping-fox
services:

  shipping:
    container_name: shipping
    image: docker.gpeter.com/shipping:latest
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_SECURITY_USER_NAME=admin
      - SPRING_SECURITY_USER_PASSWORD=admin
    ports:
      - "8081:8080"
      - "8001:8000"
    restart: on-failure

networks:
  default:
    name: shipping
    driver: bridge
